---
# tasks file for prometheus

- name: prometheus | create directories
  become: yes
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - /etc/prometheus
  - /etc/prometheus/rules
  - /etc/prometheus/targets

- name: prometheus | prometheus configuration file
  become: yes
  template:
    dest: /etc/prometheus/prometheus.yml
    force: yes
    src: etc-prometheus-prometheus-yml.j2
  register: prometheus_configuration

- name: prometheus | prometheus alert rules
  become: yes
  copy:
    dest: /etc/prometheus/rules/default-alert.rules
    force: yes
    src: etc-prometheus-default-alert.rules
  register: prometheus_alert_rules

- name: prometheus | alertmanager configuration file
  become: yes
  template:
    dest: /etc/prometheus/alertmanager.yml
    force: yes
    src: etc-prometheus-alertmanager-yml.j2
  register: prometheus_alertmanager_configuration

- name: prometheus | blackbox configuration file
  become: yes
  copy:
    dest: /etc/prometheus/blackbox-exporter.yml
    force: yes
    src: etc-prometheus-blackbox-exporter.yml
  register: prometheus_blackboxexporter_configuration

- name: prometheus | file sd configs
  become: yes
  template:
    dest: /etc/prometheus/targets/{{ item.groupname }}.yml
    force: yes
    src: file_sd_config-template-yml.j2
  with_items:
    - "{{ prometheus_targets }}"

# Docker containers

- name: prometheus | docker-python
  become: yes
  yum:
    name: docker-python
    state: present

- name: pull an image
  become: yes
  docker_image:
    name: "{{ item }}"
  with_items:
  - prom/alertmanager
  - prom/blackbox-exporter
  - prom/prometheus

- name: prometheus | docker alertmanager
  become: yes
  docker_container:
    command: >
      -config.file=/etc/prometheus/alertmanager.yml
      -storage.path=/alertmanager
    image: prom/alertmanager
    name: alertmanager
    published_ports:
    - 9093:9093
    #read_only: True
    recreate: "{{ prometheus_alertmanager_configuration.changed }}"
    restart_policy: on-failure
    state: started
    volumes:
    - /etc/prometheus/alertmanager.yml:/etc/prometheus/alertmanager.yml:ro
    - alertmanager-data:/alertmanager

- name: prometheus | docker blackbox-exporter
  become: yes
  docker_container:
    command: "-config.file=/etc/prometheus/blackbox-exporter.yml"
    image: prom/blackbox-exporter
    name: blackbox-exporter
    published_ports:
    - 9115:9115
    #read_only: True
    recreate: "{{ prometheus_blackboxexporter_configuration.changed }}"
    restart_policy: on-failure
    state: started
    volumes:
    - /etc/prometheus/blackbox-exporter.yml:/etc/prometheus/blackbox-exporter.yml:ro

- name: prometheus | docker prometheus
  become: yes
  docker_container:
    command: >
      -config.file=/etc/prometheus/prometheus.yml
      -storage.local.path=/prometheus
      -web.console.libraries=/usr/share/prometheus/console_libraries
      -web.console.templates=/usr/share/prometheus/consoles
      -alertmanager.url=http://alertmanager:9093
    image: prom/prometheus
    links:
    - alertmanager:alertmanager
    - blackbox-exporter:blackbox-exporter
    name: prometheus
    published_ports:
    - 9090:9090
    #read_only: True
    recreate: "{{ prometheus_configuration.changed or prometheus_alert_rules.changed }}"
    restart_policy: on-failure
    state: started
    volumes:
    # We could mount /etc/prometheus instead but the Docker image contains
    # additional (optional) files
    - /etc/prometheus/rules:/etc/prometheus/rules:ro
    - /etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    - /etc/prometheus/targets:/etc/prometheus/targets:ro
    - prometheus-data:/prometheus
