---
# tasks file for prometheus

- include: components.yml

# Flush handlers to ensure systemd is reloaded
- name: prometheus | flush systemd handlers
  meta: flush_handlers

- name: prometheus | prometheus configuration file
  become: yes
  template:
    dest: /etc/prometheus/prometheus.yml
    force: yes
    src: etc-prometheus-prometheus-yml.j2
  when: "{{ 'prometheus' in prometheus_components }}"
  notify:
  - restart prometheus

- name: prometheus | prometheus alert rules
  become: yes
  copy:
    dest: /etc/prometheus/alert.rules
    force: yes
    src: etc-prometheus-alert.rules
  when: "{{ 'prometheus' in prometheus_components }}"
  notify:
  - restart prometheus

- name: prometheus | alertmanager configuration file
  become: yes
  template:
    dest: /etc/prometheus/alertmanager.yml
    force: yes
    src: etc-prometheus-alertmanager-yml.j2
  when: "{{ 'alertmanager' in prometheus_components }}"
  notify:
  - restart alertmanager

- name: prometheus | blackbox configuration file
  become: yes
  copy:
    dest: /etc/prometheus/blackbox-exporter.yml
    force: yes
    src: etc-prometheus-blackbox-exporter.yml
  when: "{{ 'blackbox_exporter' in prometheus_components }}"
  notify:
  - restart blackbox-exporter

- name: prometheus | enable and start systemd components
  become: yes
  service:
    enabled: yes
    name: "{{ prometheus_component_downloads[item].service }}.service"
    state: started
  with_items:
  - "{{ prometheus_components }}"

# TODO: restart if systemd.service files changed?
