---
# handlers file for prometheus

- name: reload systemd
  become: yes
  command: systemctl daemon-reload

- name: restart prometheus
  become: yes
  service:
    name: prometheus
    state: restarted

- name: restart alertmanager
  become: yes
  service:
    name: prometheus-alertmanager
    state: restarted

- name: restart blackbox-exporter
  become: yes
  service:
    name: prometheus-blackbox-exporter
    state: restarted
